print("Example:")
print("")
print("White-capped rocky cliffs and steppes")
print("Are equal to the soul of our people.")
print("For countless centuries, our fathers")
print("Have lived in and kept the Ala-Too.")
print("")
print("March forward, Kyrgyz people,")
print("On the way to freedom!")
print("Prosperity and progress,")
print("Your own fate is in your hands!")